version: '3'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=guide.settings.local
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:10
